### ISSUE TITLE
Audio support 

### ISSUE THREAD

**Issue by bil-ash** [rwillenbacher/y262#1]
Does this encoder support encoding audio(mp2) also for mpeg1 format? If no, do  you know any open source library which does so?

https://github.com/phoboslab/pl_mpeg/issues/15

**Comment by rwillenbacher** [comment]
Sadly y262 is only doing video (somewhat slow too), so no audio and no muxing to PS/TS/MP4. 

No ffmpeg eh ?

For Mpeg Audio I know lame [https://lame.sourceforge.io](https://lame.sourceforge.io). Maybe [https://github.com/njh/twolame](https://github.com/njh/twolame) for layer2 only. I have not done any thorough investigation about these though.

For Muxing Mpeg-1 mplex should work, its no library though I think. It is part of [https://mjpeg.sourceforge.io](https://mjpeg.sourceforge.io). Prepare for time travel, I used this in the 90s and it worked, cant say much about it now. Otherwise I fear you have to use Google to find an open source mpeg-1 program stream multiplexer.

Good Luck. :>

**Comment by bil-ash** [comment]
I do have ffmpeg but wanted something lighter. Seems like I have to use ffmpeg only. Thanks for all the info. Closing the issue
